services:
  php:
    build:
      context: .
      dockerfile: Dockerfiles/php.dockerfile
    volumes:
      - ./app:/var/www/html
      - ./Dockerfiles/entrypoint.sh:/entrypoint.sh # Ensure entrypoint is inside container
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    command: [ "sh", "-c", "/entrypoint.sh" ]
    healthcheck:
      test: [ "CMD", "php", "artisan", "migrate:status" ]
      interval: 10s
      retries: 5

  node:
    build:
      context: .
      dockerfile: Dockerfiles/node.dockerfile
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5173:5173"  # Expose Vite on port 5173
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      php:
        condition: service_healthy  # Wait until PHP is ready
#  mysql:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: laravel
#      MYSQL_USER: laravel
#      MYSQL_PASSWORD: secret
#    ports:
#      - "3306:3306"
#    volumes:
#      - db-data:/var/lib/mysql

volumes:
  db-data:
