services:
  php:
    build:
      context: .
      dockerfile: Dockerfiles/php.dockerfile
    volumes:
      - ./app:/var/www/html
      - ./Dockerfiles/entrypoint.sh:/entrypoint.sh
    working_dir: /var/www/html
    ports:
      - "1305:1305"  # Laravel
      - "5173:5173"  # Vite
    command: [ "sh", "-c", "/entrypoint.sh" ]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
